Traceback (most recent call last):
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 626, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/util.py", line 96, in ensure_async
    result = await obj
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/jupyter_client/channels.py", line 230, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/envs/test/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 838, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 650, in _async_poll_for_reply
    await self._async_handle_timeout(timeout, cell)
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 697, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 125 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['from dymos.models.atmosphere import USatm1976Comp', 'from dymos.examples.aircraft_steady_flight.dynamic_pressure_comp import DynamicPressureComp', 'from dymos.examples.min_time_climb.aero.lift_drag_force_comp import LiftDragForceComp', 'from dymos.models.eom.flight_path_eom_2d import FlightPathEOM2D', 'from dymos.examples.water_rocket.water_engine_comp import _WaterThrust']
...
['plot_propelled_ascent(p, exp_out)', 'plot_trajectory(p, exp_out)', 'plot_states(p, exp_out)', '', 'plt.show()']
-------------------

